; VisionFlow — Configuração Unificada do PlatformIO
; Projeto de Hardware: ESP32 Principal (esp32_main) e ESP32-CAM (esp32_cam)

[platformio]
default_envs = esp32_main, esp32_cam

[env:esp32_main]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
build_src_filter = +<../esp32_main/src/>
build_flags = 
    -I esp32_main/include
lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4

[env:esp32_cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I esp32_cam/include
build_src_filter = +<../esp32_cam/src/>
